## Working with Missing Data in Pandas

In [3]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [5]:
data = {
  'names' : ["Adam","Bob","Charles","Daisy","Edward","Fiona","Graham"],
  'age' : [20,21,23,19,29,27,26],
  'gender' : ['M','M','M','F','M','F','M'],
  'rank' : [4,2,6,1,3,5,7]
}
ranking_df = DataFrame(data)
ranking_df.iloc[3,:] = np.nan
ranking_df.iloc[2:5,1] = np.nan 
ranking_df.iloc[3:6,3] = np.nan

In [6]:
ranking_df

     names   age gender  rank
0     Adam  20.0      M   4.0
1      Bob  21.0      M   2.0
2  Charles   NaN      M   6.0
3      NaN   NaN    NaN   NaN
4   Edward   NaN      M   NaN
5    Fiona  27.0      F   NaN
6   Graham  26.0      M   7.0

In [11]:
ranking_df.isna()
ranking_df.notna()
ranking_df.isnull()
ranking_df.notnull()

   names    age  gender   rank
0   True   True    True   True
1   True   True    True   True
2   True  False    True   True
3  False  False   False  False
4   True  False    True  False
5   True   True    True  False
6   True   True    True   True

In [13]:
ranking_df[pd.isnull(ranking_df['age'])]

     names  age gender  rank
2  Charles  NaN      M   6.0
3      NaN  NaN    NaN   NaN
4   Edward  NaN      M   NaN

In [15]:
type(pd.isnull(ranking_df['age']))

pandas.Series

In [17]:
ranking_df.fillna('Not Missing')

         names          age       gender         rank
0         Adam         20.0            M          4.0
1          Bob         21.0            M          2.0
2      Charles  Not Missing            M          6.0
3  Not Missing  Not Missing  Not Missing  Not Missing
4       Edward  Not Missing            M  Not Missing
5        Fiona         27.0            F  Not Missing
6       Graham         26.0            M          7.0

In [23]:
#The method argument is demised now, use ffill or bfill instead
#ranking_df.fillna(method='pad')
ranking_df.ffill()

     names   age gender  rank
0     Adam  20.0      M   4.0
1      Bob  21.0      M   2.0
2  Charles  21.0      M   6.0
3  Charles  21.0      M   6.0
4   Edward  21.0      M   6.0
5    Fiona  27.0      F   6.0
6   Graham  26.0      M   7.0

In [24]:
ranking_df.bfill()

     names   age gender  rank
0     Adam  20.0      M   4.0
1      Bob  21.0      M   2.0
2  Charles  27.0      M   6.0
3   Edward  27.0      M   7.0
4   Edward  27.0      M   7.0
5    Fiona  27.0      F   7.0
6   Graham  26.0      M   7.0

In [27]:
ranking_df.iloc[:,[1,3]].interpolate(method='linear')

    age  rank
0  20.0  4.00
1  21.0  2.00
2  22.5  6.00
3  24.0  6.25
4  25.5  6.50
5  27.0  6.75
6  26.0  7.00

In [28]:
ranking_df.dropna()

    names   age gender  rank
0    Adam  20.0      M   4.0
1     Bob  21.0      M   2.0
6  Graham  26.0      M   7.0

In [29]:
ranking_df.dropna(how='all')

     names   age gender  rank
0     Adam  20.0      M   4.0
1      Bob  21.0      M   2.0
2  Charles   NaN      M   6.0
4   Edward   NaN      M   NaN
5    Fiona  27.0      F   NaN
6   Graham  26.0      M   7.0

In [32]:
ranking_df.dropna(axis=1,how='all')

     names   age gender  rank
0     Adam  20.0      M   4.0
1      Bob  21.0      M   2.0
2  Charles   NaN      M   6.0
3      NaN   NaN    NaN   NaN
4   Edward   NaN      M   NaN
5    Fiona  27.0      F   NaN
6   Graham  26.0      M   7.0

### Filling missing values using fillna(), replace() and interpolate()